

### LOGIN
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "harshika.jain@example.com",
  "password": "123456"
}

###

# ### GET USER DATA
#  GET http://localhost:3000/api/chat/get
#  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NmY3MmNkZDIyNDBkNjJiNzhkY2UzMiIsImlhdCI6MTc2ODkxMzYzMiwiZXhwIjoxNzcxNTA1NjMyfQ.fV8Cs8gLX7OVSU70FpBM32RaNiROwDcn27et9Rx4Ckc

POST http://localhost:3000/api/message/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NmY3MmNkZDIyNDBkNjJiNzhkY2UzMiIsImlhdCI6MTc2ODkxMzYzMiwiZXhwIjoxNzcxNTA1NjMyfQ.fV8Cs8gLX7OVSU70FpBM32RaNiROwDcn27et9Rx4Ckc
Content-Type: application/json

{
  "chatId": "6970e74c76eadd2882507273",
  "prompt": "a boy climbing stairs", 
  "isPublished": true

}

